modLoader = "javafml"
loaderVersion = "[32,)"
license = "LGPLv3"

[[mods]]
modId = "caffeineconfig"
version = "${version}"
displayName = "CaffeineConfig-Forge"
displayURL="https://github.com/TexTrueStudio/CaffeineConfig"
logoFile="icon.png"
credits="CafffeineMC"
authors="TexTrue, TexTrueStudio, BocchiKessokuTeam"
description = '''
CaffeineConfig Unofficial forge port.

A small library providing a config system that allows the user and other mods to disable mixins from being applied.
'''

[[dependencies.caffeineconfig]]
modId = "forge"
mandatory = true
versionRange = "[32,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.caffeineconfig]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16,)"
ordering = "NONE"
side = "BOTH"