modLoader = "javafml"
loaderVersion = "[32,)"
license = "LGPLv3"

[[mods]]
modId = "caffeineconfig"
version = "${version}"
displayName = "ColaConfig"
displayURL="https://github.com/TexTrueStudio/ColaMixinConfig"
logoFile="icon.png"
credits="CafffeineMC"
authors="TexTrue, TexTrueStudio, BocchiKessokuTeam"
description = '''
CaffeineConfig Unofficial forge port.

A small library providing a config system that allows the user and other mods to disable mixins from being applied.
'''