modLoader = "javafml"
loaderVersion = "[39,)"
license = "LGPLv3"

[[mods]]
modId = "caffeineconfig_test"
version = "${version}"
displayName = "ColaConfig Example Mod"
displayURL="https://changeme.dev/"
logoFile="icon.png"
credits="CafffeineMC"
authors="Me!"
description = '''
CaffeineConfig Unofficial forge port.

A testmod for CaffeineConfig also serving as an example.
'''

[[dependencies.caffeineconfig_test]]
modId = "forge"
mandatory = true
versionRange = "[39,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.caffeineconfig_test]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,)"
ordering = "NONE"
side = "BOTH"